# This is a generated file. Not intended for manual editing.
services:
  aula-cos:
    build:
      context: "/home/thacio/RiderProjects/aula-COS"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/aula-COS.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "aula-cos:dev"
    ports: []
    volumes:
    - "/home/thacio/.nuget/packages:/home/app/.nuget/packages"
    - "/home/thacio/RiderProjects/aula-COS:/app:rw"
    - "/home/thacio/RiderProjects/aula-COS:/src:rw"
    working_dir: "/app"
